autopollservice always update cache at first poll
configcat/common-js pull request #44
Opened 2022-04-01 16:34 UTC by endret

### Describe the purpose of your pull request

AutoPollConfigService will always update the cache at the first poll with the latest `TimeStamp` value even if it does not change. The `GetConfig` method will only block while the fetch logic returns the result or for the time specified in the `maxInitWaitTimeSeconds` parameter (default: 5000 ms).

### Related issues (only if applicable)

https://github.com/configcat/common-js/issues/43

### Requirement checklist (only if applicable)

- [X] I have covered the applied changes with automated tests.
- [X] I have executed the full automated test set against my changes.
- [X] I have validated my changes against all supported platform versions.
- [X] I have read and accepted the [contribution agreement](https://github.com/configcat/legal/blob/main/contribution-agreement.md).

2022-04-01 16:49 UTC, sigewuzhere requested changes

2022-04-01 16:49 UTC, sigewuzhere commented on test/ConfigServiceBaseTests.ts
> +    it("AutoPollConfigService - backgroundworker only - config doesn't exit in the cache - invokes 'cache.set' operation only once", async () => {
```suggestion
    it("AutoPollConfigService - backgroundworker only - config doesn't exist in the cache - invokes 'cache.set' operation only once", async () => {
```

2022-04-01 16:49 UTC, sigewuzhere commented on test/ConfigServiceBaseTests.ts
> +    it("AutoPollConfigService - ProjectConfig is cached and fetch returns same value - should invokes 'cache.set' operation only once (at first)", async () => {
```suggestion
    it("AutoPollConfigService - ProjectConfig is cached and fetch returns same value - should invoke the 'cache.set' operation only once (at first)", async () => {
```

2022-04-01 16:49 UTC, sigewuzhere commented on test/ConfigServiceBaseTests.ts
> +    it("AutoPollConfigService - ProjectConfigs are same but cache stores older config than poll interval - Should wait until cache update with new timestamp", async () => {
```suggestion
    it("AutoPollConfigService - Cached config is the same as ProjectConfig but older than the polling time - Should wait until the cache is updated with the new timestamp", async () => {
```

2022-04-01 16:49 UTC, sigewuzhere commented on test/ConfigServiceBaseTests.ts
> +    it("AutoPollConfigService - ProjectConfigs are same but cache stores not older config than poll interval - Should return cached item", async () => {
```suggestion
    it("AutoPollConfigService - Cached config is the same as ProjectConfig but older than the polling time - Should return cached item", async () => {
```

2022-04-04 18:09 UTC, sigewuzhere approved these changes

2022-04-06 07:28 UTC, laliconfigcat approved these changes

2022-04-22 07:13 UTC, merged