Improves config fetcher logic
configcat/common-js pull request #66
Opened 2022-11-29 10:20 UTC by adams85

### Describe the purpose of your pull request

Breaking changes:
* Changes `IConfigFetcher.fetchLogic` to return a `Promise` instead of accepting a callback. Also changes the data structure returned (`IFetchResponse` instead of `FetchResult`).
* Changes `ProjectConfig.equals` to fall back to comparing the actual configs when both ETags are not available.

### Requirement checklist (only if applicable)

- [x] I have covered the applied changes with automated tests.
- [x] I have executed the full automated test set against my changes.
- [x] I have validated my changes against all supported platform versions.
- [x] I have read and accepted the [contribution agreement](https://github.com/configcat/legal/blob/main/contribution-agreement.md).

2022-12-06 12:29 UTC, laliconfigcat requested changes

2022-12-06 12:29 UTC, laliconfigcat commented on src/ConfigServiceBase.ts
> +                case 404: // Not Found
Please also add 403 to this case, as we may block the config.json downloads with firewall rules and that returns a 403.

2022-12-12 19:54 UTC, laliconfigcat approved these changes

2022-12-12 19:56 UTC, laliconfigcat requested changes
Just to remove my approve. Just saw that tests are failing.

2022-12-12 20:19 UTC, laliconfigcat approved these changes

2022-12-13 19:35 UTC, endret approved these changes

2022-12-13 20:43 UTC, merged