#68 add pollIntervalSeconds isNaN validation
configcat/common-js pull request #69
Opened 2022-12-02 15:59 UTC by ddemydenko

add maxInitWaitTimeSeconds isNaN validation
FIx issue 68
### Describe the purpose of your pull request

Passing NaN as pollIntervalSeconds interval causes setTimeout infinity call, that in turn million request to config-cat CDN
- List the **user facing** changes and if any, add the @configcat/ux team as reviewer.

### Related issues (only if applicable)

Provide links to issues relating to this pull request
https://github.com/configcat/common-js/issues/68
### Requirement checklist (only if applicable)

- [x] I have covered the applied changes with automated tests.
- [x] I have executed the full automated test set against my changes.
- [x] I have validated my changes against all supported platform versions.
- [x] I have read and accepted the [contribution agreement](https://github.com/configcat/legal/blob/main/contribution-agreement.md).

2022-12-02 21:57 UTC, endret commented
Hi @ddemydenko,


If you try to pass `null` or `undefinied` to the `pollIntervalSeconds` variables the following [lines](https://github.com/configcat/common-js/pull/69/files#diff-eb413ace3ce69d5eb343430c4e3fd651cc234dad5eb863c5e9d5eb605bef3617L147) should handle this and the default value will use (60 seconds).

If you agree I close this PR.

Regards,
Endre

2022-12-03 07:45 UTC, ddemydenko commented
> Hi @ddemydenko,
> 
> If you try to pass `null` or `undefinied` to the `pollIntervalSeconds` variables the following [lines](https://github.com/configcat/common-js/blob/master/src/ConfigCatClientOptions.ts#L147) should handle this and the default value will use (60 seconds).
> 
> If you agree I close this PR.
> 
> Regards, Endre

Hi, @endret the NaN is not undefined neither null. I faced with this on production and got an unexpected billing.
When you write code with typescript it is ok. But then it compiles to javascript and uses in docker container. So when for some reason(typo mistaken) the env variable was not assigned it caused. to poling with 0 timeout duration.
Here is an example:

```typescript
const configCatConfig: ConfigCatProviderConfig = {
      sdkKey: config.get('CONFIG_CAT_SDK_KEY'),
      pollIntervalSeconds: +config.get('POLL_INTERVAL_SECONDS'),
};
const ConfigCatClient = createClient(configCatConfig);
```

During deployment POLL_INTERVAL_SECONDS was not assigned. This is env vars so it is not under control of typescript code.

`+undefined` will converted to NaN as result poling without duration.

2022-12-03 22:24 UTC, endret commented
Thank you for the clarification. Now I see your issue.
I have some concerns with your solution. It is not handled when you pass a `boolean` or `string` with a whitespace value.

I guess the `typeof` or the `.isFinite`could be good for it.

Consider implementing the mentioned solution above, and please create a proper test for the possible cases.

2022-12-05 13:22 UTC, ddemydenko commented
> Thank you for the clarification. Now I see your issue. I have some concerns with your solution. It is not handled when you pass a `boolean` or `string` with a whitespace value.
> 
> I guess the `typeof` or the `.isFinite`could be good for it.
> 
> Consider implementing the mentioned solution above, and please create a proper test for the possible cases.

@endret done

2022-12-06 00:05 UTC, endret requested changes

2022-12-06 00:05 UTC, endret commented on test/ConfigCatClientOptionsTests.ts
> +    myConfig.set('pollIntervalSeconds', undefined);
```suggestion
    myConfig.set('pollIntervalSeconds', NaN);
```

2022-12-06 00:05 UTC, endret commented on test/ConfigCatClientOptionsTests.ts
> +      new AutoPollOptions("APIKEY", "common", "1.0.0", { pollIntervalSeconds: +(myConfig.get('pollIntervalSeconds')) }, null);
```suggestion
      new AutoPollOptions("APIKEY", "common", "1.0.0", { pollIntervalSeconds: myConfig.get('pollIntervalSeconds') }, null);
```

2022-12-06 22:51 UTC, endret approved these changes

2022-12-06 22:57 UTC, merged