Proposal/improve type safety
configcat/common-js pull request #73
Opened 2022-12-14 11:30 UTC by adams85

### Describe the purpose of your pull request

As pointed out by https://github.com/configcat/common-js/pull/71, the `IConfigCatClient` interface is not optimal concerning the `getValue`/`getValueAsync`, `getValueDetails`/`getValueDetailsAsync` methods. These methods take a default value and return `any`, so users get no help from the TS compiler at all: they can use mismatching types without a compile-time or run-time warning. For example
```js
let value: boolean = await client.getValueAsync("KEY", 1);
```
compiles without errors but the actual (run-time) type of the variable `value` can be totally different from its compile-time type (`boolean`) because
1. when the key doesn't exist, `1` is returned which is not a `boolean` value but a `number`.
2. when the key exists, nothing guarantees that the type of the evaluated setting is actually `boolean`. Currently we don't have such checks in place which would enforce that the default value and the evaluated value have the same type.

https://github.com/configcat/common-js/pull/71 suggests making the methods in question generic, which would solve the first problem as in that case TS compiler would enforce that the types of the default value and the return value match:
```js
let value: boolean = await client.getValueAsync("KEY", 1); // Compile error
let value2: boolean = await client.getValueAsync("KEY", false); // OK
```

However, this doesn't address the second problem as it still not guarantees that `value2` holds a `boolean` value in all cases. When the setting exists, the evaluated value can be e.g. a `string`. In this regard this API may be even worse as it suggests to the user that the assignment is type-safe and variable `value` must be a `boolean`.

This PR aims to address both of the problems:
- [Makes the signatures of these methods generic](https://github.com/configcat/common-js/commit/ab2ad5908cf96414c208f33e73fc1ef7d1f4c4db#diff-099ddaac3d178ac178a4187aeb32c9c4215da7f98982a88ed31125a4c6eac6c0R21-R32) so TS compiler enforces that the types of default value and return value match.
- [Disallows default values other than `boolean`, `number`, `string`, `null` and `undefined`](https://github.com/configcat/common-js/commit/ab2ad5908cf96414c208f33e73fc1ef7d1f4c4db#diff-099ddaac3d178ac178a4187aeb32c9c4215da7f98982a88ed31125a4c6eac6c0R320). (This prevents users from passing non-sense default values to these methods. We may relax this check by using a warning instead if we want to reduce the possibility of breaking the behavior of existing user code.)
- [Requires that the types of default value and evaluated setting value match when default value is not `null` and `undefined`](https://github.com/configcat/common-js/commit/ab2ad5908cf96414c208f33e73fc1ef7d1f4c4db#diff-30d7cdce233fb6777b0a0a686b7c31f2c426d0530cfe112dee0ee8ff10b9ce8cR611-R613). (This ensures that TS compiler's type check is enforced at run-time, that is, the run-time type of the return value corresponds to its reported compile-time type under all circumstances.  We may relax this check by using a warning instead if we want to reduce the possibility of breaking the behavior of existing user code.)

Examples:

```js
const client = getClient("SDK-KEY", PollingMode.AutoPoll);

const a1 = await client.getValueAsync("KEY", false); // Variable's inferred compile-time type: boolean / Run-time type: boolean (enforced by checks)
const a2 = await client.getValueAsync("KEY", null); // Variable's inferred compile-time type: string | number | boolean | null / Run-time type: null (if KEY is not present) | boolean | number | string (depending on the actual setting value)
const a3 = await client.getValueAsync("KEY", undefined); // Variable's inferred compile-time type: string | number | boolean | undefined / Run-time type: undefined (if KEY is not present) | boolean | number | string (depending on the actual setting value)

const b1 = await client.getValueAsync<boolean>("KEY", false); // Variable's inferred compile-time type: boolean / Run-time type: boolean (enforced by checks)
const b2 = await client.getValueAsync<boolean>("KEY", null); // Compile error: Argument of type 'null' is not assignable to parameter of type 'boolean'.
const b3 = await client.getValueAsync<boolean>("KEY", undefined); // Compile error: Argument of type 'undefined' is not assignable to parameter of type 'boolean'.

const c1 = await client.getValueAsync<boolean | null>("KEY", false); // Variable's inferred compile-time type: string | number | boolean | null / Run-time type: boolean (enforced by checks)
const c2 = await client.getValueAsync<boolean | null>("KEY", null); // Variable's inferred compile-time type: string | number | boolean | null / Run-time type: null (if KEY is not present) | boolean | number | string (depending on the actual setting value)
const c3 = await client.getValueAsync<boolean | null>("KEY", undefined); // Compile error: Argument of type 'undefined' is not assignable to parameter of type 'boolean | null'.

const d1 = await client.getValueAsync<boolean | undefined>("KEY", false); // Variable's inferred compile-time type: string | number | boolean | undefined / Run-time type: boolean (enforced by checks)
const d2 = await client.getValueAsync<boolean | undefined>("KEY", null); // Compile error: Argument of type 'null' is not assignable to parameter of type 'boolean | undefined'.
const d3 = await client.getValueAsync<boolean | undefined>("KEY", undefined); // Variable's inferred compile-time type: string | number | boolean | undefined / Run-time type: undefined (if KEY is not present) | boolean | number | string (depending on the actual setting value)

const e1 = await client.getValueAsync<boolean | string>("KEY", false); // Variable's inferred compile-time type: string | boolean / Run-time type: boolean (enforced by checks)
const e2 = await client.getValueAsync<boolean | string>("KEY", null); // Compile error: Argument of type 'null' is not assignable to parameter of type 'string | boolean'.
const e3 = await client.getValueAsync<boolean | string>("KEY", undefined); // Compile error: Argument of type 'undefined' is not assignable to parameter of type 'string | boolean'.

const f1 = await client.getValueAsync<any>("KEY", false); // Variable's inferred compile-time type: any / Run-time type: boolean (enforced by checks)
const f2 = await client.getValueAsync<any>("KEY", null); // Variable's inferred compile-time type: any / null (if KEY is not present) | boolean | number | string (depending on the actual setting value)
const f3 = await client.getValueAsync<any>("KEY", undefined); // Variable's inferred compile-time type: any / Run-time type: undefined (if KEY is not present) | boolean | number | string (depending on the actual setting value)

const err1: boolean = await client.getValueAsync("KEY", 123); // Compile error: Type 'number' is not assignable to type 'boolean'.
const err2: boolean = await client.getValueAsync("KEY", null); // Compile error: Type 'string | number | boolean | null' is not assignable to type 'boolean'. Type 'null' is not assignable to type 'boolean'.
const err3: boolean = await client.getValueAsync<boolean | null>("KEY", false); // Compile error: Type 'string | number | boolean | null' is not assignable to type 'boolean'.
const err4: boolean = await client.getValueAsync<boolean | null>("KEY", null); // Compile error: Type 'string | number | boolean | null' is not assignable to type 'boolean'.
```

Cases `c1` and `d1` are not optimal as the return type could be simply `boolean`. However, I don't know of a way to express this with TS type system. It may be possible but probably it'd be pretty complicated, so I think we can ignore this because these are pretty marginal cases anyway.

The PR also corrects the signature of the `getVariationId`/`getVariationIdAsync` and the behavior of `getAllVariationIds`/ `getAllVariationIdsAsync` methods.

**These changes are non-negligible breaking changes**, so I'm pinging @configcat/ux-qa-team to also revie [...]

2022-12-15 14:38 UTC, sigewuzhere requested changes

2022-12-15 14:38 UTC, sigewuzhere commented on src/RolloutEvaluator.ts
> +    throw new Error("Default value is only allowed to be a boolean, number, string, null or undefined value.");
```suggestion
    throw new Error("The default value must be boolean, number, string, null or undefined.");
```

2022-12-15 14:38 UTC, sigewuzhere commented on src/RolloutEvaluator.ts
> +        throw new Error(`The type of a setting must match the type of the setting's default value.\nSetting's type was ${typeof defaultValue} but the default value's type was ${typeof evaluationDetai
```suggestion
        throw new Error(`The type of a setting must match the type of the given default value.\nThe setting's type was ${typeof defaultValue},the given default value's type was ${typeof evaluationDetails.value}.\nPlease pass a corresponding default value type.`);
```

2023-01-02 15:58 UTC, laliconfigcat approved these changes

2023-01-02 21:00 UTC, sigewuzhere approved these changes

2023-01-03 10:21 UTC, merged